# Generated by Django 2.2.12 on 2022-04-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_myrest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyRest',
        ),
    ]
