# Generated by Django 2.2.12 on 2022-03-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='class_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
