# Generated by Django 2.2.12 on 2022-03-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20220313_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='locations',
            new_name='stops',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='time',
        ),
        migrations.AddField(
            model_name='flights',
            name='dates',
            field=models.ManyToManyField(to='flights.Dates'),
        ),
        migrations.AddField(
            model_name='flights',
            name='times',
            field=models.ManyToManyField(to='flights.Times'),
        ),
    ]
