# Generated by Django 2.2.12 on 2022-03-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20220317_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='dates',
        ),
        migrations.AlterField(
            model_name='times',
            name='time',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
