# Generated by Django 2.2.12 on 2022-03-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20220317_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='class_type',
        ),
    ]
