# Generated by Django 2.2.12 on 2022-03-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
