# Generated by Django 2.2.12 on 2022-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220306_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
