# Generated by Django 2.2.12 on 2022-04-14 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_myrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='myrest',
            name='rest',
            field=models.ManyToManyField(to='food.CopyRes'),
        ),
        migrations.AlterField(
            model_name='myrest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
